name: Chaining workflow

on:
  workflow_dispatch:
    inputs:
      input_1:
        description: "input uno"
        type: string

jobs:
  lavoro_1:
    runs-on: ubuntu-latest
    steps:
      - name: output something
        run: echo "input uno vale + ${{inputs.input_1}}"
