name: page_32_workflow

on:
  repository_dispatch:
    types: [event3, event4]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print var1
        run: echo "var1 = ${{ github.event.client_payload.var1 }} \ var2 = ${{ github.event.client_payload.var1 }}"
