name: Page 32 workflow

on: 
  repository_dispatch:
    types: [event3, event4]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name:  Print var1
        run: echo "var1 : {{ github.event3.payload.client_payload_var1}}"


