# Example workflow file
name: Ruggero workflow

on:
  repository_dispatch:
    types: [event1, event2]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - debug
          - warning
          - error

      variabile_a:
        description: variabile a
        required: true
        type: integer

jobs:
  Esempio:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world!"
      - name: mah
        run: git clone https://github.com/ruggeromontesi/GithubActionsInAction.git

      - name: mah-1
        run: cd ./GithubActionsInAction && ls -al

      - name: mah-03
        run: rm -rf ./GithubActionsInAction

      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: install
        run: npm install
      - name: build
        run: npm run build
          
  job2:
    needs: Esempio
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: cd ./GithubActionsInAction && npm run dev
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: stop
      - run: sleep 30 && npx kill-port 5173
