# Example workflow file
name: Ruggero workflow

on:
  repository_dispatch:
    types: [event1, event2]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - debug
          - warning
          - error

      variabile_a:
        description: variabile a
        required: true
        type: integer

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repository
        run: git clone https://github.com/ruggeromontesi/GithubActionsInAction.git

      - name: cd into folder
        run: cd ./GithubActionsInAction && ls -al

      - name: delete folder
        run: rm -rf ./GithubActionsInAction

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: install
        run: npm install

      - name: build
        run: npm run build

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: run
        run: ls -al
      - name: run
        run: npm run dev
